from .aluno import Aluno
from .atribuicao import Atribuicao
from .configuracao import Configuracao
from .diario import Diario
from .disciplina import Disciplina
from .escola import Escola
from .horario import Horario
from .mensalidade import Mensalidade
from .nota import Nota
from .notificacao import Notificacao
from .ponto_professor import PontoProfessor
from .presenca import Presenca
from .turma import Turma
from .usuario import Usuario