from .aluno import Aluno
from .disciplina import Disciplina
from .escola import Escola
from .mensalidade import Mensalidade
from .nota import Nota
from .turma import Turma
from .usuario import Usuario
from .presenca import Presenca
from .configuracao import Configuracao
from .atribuicao import Atribuicao
from .horario import Horario
from .diario import Diario
from .ponto_professor import PontoProfessor