"""Initial migration

Revision ID: 426659e5bea5
Revises: 8e62f51b1a9b
Create Date: 2026-02-10 12:46:29.243702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426659e5bea5'
down_revision: Union[str, Sequence[str], None] = '8e62f51b1a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarios', sa.Column('escola_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'diarios', 'escolas', ['escola_id'], ['id'])
    op.add_column('disciplinas', sa.Column('escola_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'disciplinas', 'escolas', ['escola_id'], ['id'])
    op.add_column('notas', sa.Column('escola_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notas', 'escolas', ['escola_id'], ['id'])
    op.alter_column('ponto_professores', 'escola_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('presencas', sa.Column('escola_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'presencas', 'escolas', ['escola_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presencas', type_='foreignkey')
    op.drop_column('presencas', 'escola_id')
    op.alter_column('ponto_professores', 'escola_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'notas', type_='foreignkey')
    op.drop_column('notas', 'escola_id')
    op.drop_constraint(None, 'disciplinas', type_='foreignkey')
    op.drop_column('disciplinas', 'escola_id')
    op.drop_constraint(None, 'diarios', type_='foreignkey')
    op.drop_column('diarios', 'escola_id')
    # ### end Alembic commands ###
