"""Configuração inicial

Revision ID: db569b3ba0c7
Revises: ec35ba906899
Create Date: 2026-03-30 19:18:21.667289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db569b3ba0c7'
down_revision: Union[str, Sequence[str], None] = 'ec35ba906899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'alunos', 'turmas', ['turma_id'], ['id'])
    op.create_foreign_key(None, 'atribuicoes', 'turmas', ['turma_id'], ['id'])
    op.create_foreign_key(None, 'horarios', 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'presencas', 'turmas', ['turma_id'], ['id'])
    op.create_foreign_key(None, 'turma_disciplina', 'turmas', ['turma_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'turma_disciplina', type_='foreignkey')
    op.drop_constraint(None, 'presencas', type_='foreignkey')
    op.drop_constraint(None, 'horarios', type_='foreignkey')
    op.drop_constraint(None, 'atribuicoes', type_='foreignkey')
    op.drop_constraint(None, 'alunos', type_='foreignkey')
    # ### end Alembic commands ###
